# Generated by Django 3.1 on 2021-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_adhocexecution_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('node', 'node'), ('asset', 'asset'), ('child', 'child')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TestB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('node', 'node'), ('asset', 'asset'), ('child', 'child')], db_index=True, max_length=16)),
            ],
        ),
    ]
